package main.util;

public enum OpcaoDeTela {
    INVALIDA,
    ABRIR_CONTA_PESSOA_FISICA,
    ABRIR_CONTA_PESSOA_JURIDICA,
    VOLTAR,
    ABRIR_CONTA_CORRENTE_PESSOA_FISICA,
    ABRIR_CONTA_POUPANCA_PESSOA_FISICA,
    ABRIR_CONTA_INVESTIMENTO_PESSOA_FISICA,
    ABRIR_CONTA_CORRENTE_PESSOA_JURIDICA,
    ABRIR_CONTA_INVESTIMENTO_PESSOA_JURIDICA,
}
