package main.util;

public enum Operacao {
    SAIR,
    SACAR,
    DEPOSITAR,
    TRANSFERIR,
    SALDO,
    ABRIR_CONTA_CORRENTE_PESSOA_FISICA,
    ABRIR_CONTA_POUPANCA_PESSOA_FISICA,
    ABRIR_CONTA_INVESTIMENTO_PESSOA_FISICA,
    ABRIR_CONTA_CORRENTE_PESSOA_JURIDICA,
    ABRIR_CONTA_INVESTIMENTO_PESSOA_JURIDICA,
    NENHUMA
}
