package main;

public enum Opcao {

    SAIR, ABRIR_CONTA, SACAR, DEPOSITAR, TRANSFERIR, SALDO, INVALIDA, ABRIR_CONTA_PESSOA_FISICA,
    ABRIR_CONTA_PESSOA_JURIDICA, VOLTAR, ABRIR_CONTA_CORRENTE_PESSOA_FISICA, ABRIR_CONTA_POUPANCA_PESSOA_FISICA,
    ABRIR_CONTA_INVESTIMENTO_PESSOA_FISICA, ABRIR_CONTA_CORRENTE_PESSOA_JURIDICA, ABRIR_CONTA_INVESTIMENTO_PESSOA_JURIDICA,
}
